 services:

  first:
    container_name: first
    image: first
    build:
      context: ./springboot-helloworld-docker-compose-internal-network-first
      dockerfile: Dockerfile
    environment:
      API_SECOND_URL: http://second:9090/api/v1
    ports:
      - 8080:8080

  second:
    container_name: second
    image: second
    build:
      context: ./springboot-helloworld-docker-compose-internal-network-second
      dockerfile: Dockerfile
    ports:
      - 9090:9090